### PR TITLE
Add/Remove users from tickets

### PR DESCRIPTION
**Pull request by asapcatftw**
While using the bot I encountered situations where I needed to add users to tickets. 
This allows users to be added/removed to/from a ticket. Currently, the command is set to the staff role.

### CODE REVIEW

**Review by Skelmis — APPROVED** [review]
I like these changes and am happy with the code. Just a couple of personal things

- [x] Change conditionals to return, then means the else can be removed
```
    if not CheckIfTicket(channel.id):
        await ctx.send("This is not a ticket! Users can only be added to a ticket channel")
    else:
        await channel.set_permissions(user, read_messages=True, send_messages=True)
        await ctx.message.delete()
```
Would then go to
```
    if not CheckIfTicket(channel.id):
        await ctx.send("This is not a ticket! Users can only be added to a ticket channel")
        return

    await channel.set_permissions(user, read_messages=True, send_messages=True)
    await ctx.message.delete()
```

- [x] Turn comments into docstrings, helps with issue #3

**Comment by Skelmis** [comment]
@asapcatftw please note your code will need to be rebased off of master to keep in accordance with #6

**Comment by asapcatftw** [comment]
I will have it fixed by tomorrow. Its been a busy weekend.

**Comment by asapcatftw** [comment]
@Skelmis 
All done let me know if something needs to be changed.

**Review by Skelmis — APPROVED** [review]

**Pull request merged**
